### ISSUE TITLE
Support AppImage

### ISSUE THREAD

**Issue by corygalyna** [ChewKeanHo/AutomataCI#126]
### Description

Since AppImage is quite famous across Linux OS.

### Expected Behavior

AppImage is available.

### Current Behavior

AppImage is not available.

**Comment by hollowaykeanho** [comment]
I'm pessimistically reluctant to support it mainly because:

1. It's better to encourage others to build static binary (signed or unsigned) rather than an ISO wrapper that relies heavily on `libfuse` to do the single executable effect. It has been lying to people that "it's a single executable" when it's not.
2. Unlike Flatpak or Snapcraft, it's not being Sandbox-ed, which is something a next-generation package ecosystem should have.
3. It encourages folks to randomly download a binary executable across the Internet without something kind of built-in authenticity checking.
4. Probonoz intentionally discriminate me in the AppImage forum (see screenshot below).

![screenshot](https://github.com/ChewKeanHo/AutomataCI/assets/7259572/ba86f023-e69d-45c1-a33b-d4221a5a836b)

5. I'm aware of Probonoz's work at OBS repository.

**Comment by corygalyna** [comment]
Ahh isn't it unfair to the community?

**Comment by hollowaykeanho** [comment]
Don't blame me. I did try to reach their community and founder for help but they shut me out like sinophobic or something.

If we're proceed with this idea and bump into their tech problem, are we on our own? The whole point of this project is to make `.deb`, `.rpm`, `.flatpak`, `.tar.xz`, `.nupkg` packaging and releases way seamless from the get-go. Mix them up and you'll realize there isn't much value AppImage is bringing into the table; left alone being passive aggressively assaulted by them from the start.

I'm sorry Cory. This is the way to go.

**Comment by corygalyna** [comment]
sigh. Okay.
